### ISSUE TITLE
Update Ticket schema

### ISSUE THREAD

**Issue by iamgoeldhruv** [IMGIITRoorkee/Ticketify#8]
There is no check on category on schema.Add  check on category field on ticket schema such that it able to store availabe categories only listed on 'EditTicketForm.tsx'.

**Comment by MadhavDhall** [comment]
Please assign this issue to me.
### My apporach:
I shall add enum to category field in ticket schema which shall contain only elements listed in **EditTicketForm.jsx**
Also in **EditTicketForm.jsx**, the spelling of Application Development is written wrongly as **_Application Deveopment_**. This also needs correction. 
We should proceed with both changes in my opinion.

**Comment by AyushDharDubey** [comment]
Hi @MadhavDhall,
sorry but this issue has already been addressed in an existing PR (#50). The discrepancy occurred due to an oversight on our part, as there was a duplicate issue (#13) for the same problem.
Unfortunately, we cannot afford to open a new PR for this issue.
I will now close this issue as duplicate.

Thank you for your understanding!
